### PR TITLE
Cache the allocated arrays for names and values

### LINKED ISSUE #19: Avoid allocating a new array every time in `GetValues` and `GetNames`
The `GetValues` and `GetNames` allocate a new array instead of caching it; a `private static readonly` field could be used, which would be initialized either lazily or immediately.

### PR DESCRIPTION
**Pull request by Rekkonnect**
Closes #19

### CODE REVIEW

**Comment by ercangorgulu** [comment]
Because methods returning array of values it can be problematic to return cached values.
Because if that array is manipulated somewhere on runtime, it will be changed in that lifetime.
Caching is good for performance but also need to consider returning ReadOnlySpan or IEnumerable etc.

**Comment by Elfocrash** [comment]
I didn't mention it in the video but I didn't mean that you should cache the array and return it as an array since the array is still mutable. You'd have to cache them as an immutable data structure, like an ImmutableArray and return them as something like IEnumerable. This breaks the contract, but I think it a better approach.

**Comment by AlFasGD** [comment]
I prefer the `ImmutableArray` approach because it more directly shows that the data isn't supposed to change; will push these new changes.

**Comment by Elfocrash** [comment]
@andrewlock Yeah I made a video about it and I mentioned that I'd rather have the library cache it in an immutable array and "protect" the user from messing it up, because not everyone looks at the package implementation and they will just assume that it's cached by default (well at least I assumed that and I was wrong 😂)

**Comment by andrewlock** [comment]
Yeah, that's a fair point, "pit of success" and all that 🤔 ok, you convinced me. I'm still inclined to stick to an array though:

- drop in replacement for `Enum.GetValues()`
- returning `IEnumerable`/`ICollection` don't quite fit, + array has optimised enumerators
- `ImmutableArray` not available in .NET Framework
- `Span<T>` not available everywhere

**Comment by ercangorgulu** [comment]
Giving a power to developer to break something. It is not good practice. If someone really wants to use as array they can convert and cache in their app.
Or we can give that option to developer. So on attribute we can set how we want to use and it will be generated based on that.

**Comment by YuriiBabenko** [comment]
@AlFasGD i'd assume that nobody reads recommendations from documentation. and price is too high, if a developer change array content

**Comment by andrewlock** [comment]
> Giving a power to developer to break something is not a good practice

I agree, _to an extent_. The "default" thing _shouldn't_ be the wrong thing, and you should have to try hard to break stuff.

> If someone really wants to use as array they can convert and cache in their app.

Well true, but I can make the same argument for all the other described types. And that was my reasoning for _not_ caching originally i.e. the developer knows best what patterns to use (though I think caching probably is the better option in reality).

> i'd assume that nobody reads recommendations from documentation

I agree

> price is too high, if a developer change array content

I don't agree. If you're changing array content, you're doing it wrong 🤷 That's not for this API, that's basically a rule in .NET. And the contents are `string` so they're not even mutable (which would be a reasonable mistake to make. You literally would have to do something like:

```csharp
values[0] = "something else";
```

And I'm willing to let people shoot themselves in the foot there 😉 

Plus, what's the alternative? As I mentioned [here](https://github.com/andrewlock/NetEscapades.EnumGenerators/pull/21#issuecomment-1151163698), most of the other options aren't feasible IMO.

**Comment by AnonymousRetard** [comment]
Why not return IReadOnlyList<T>? You can still use indexes with that interface (myCachedEnums[5]) and you can still access the .Count property without having to enumerate all items. I don't see how ImmutableArray would solve any problems over the IReadOnlyList as long as the internal cached array is private.

Or... you could keep the GetValues() and GetNames() methods as they are and introduce something else like properties "Values" and "Names" as well to return a cached IReadOnlyList<T> instead. I think it's generally frowned upon if properties do heavy work while it's more accepted when methods do.

**Comment by AlFasGD** [comment]
> Why not return IReadOnlyList? You can still use indexes with that interface (myCachedEnums[5]) and you can still access the .Count property without having to enumerate all items. I don't see how ImmutableArray would solve any problems over the IReadOnlyList as long as the internal cached array is private.

The problem was already mentioned being suboptimal enumeration from the returning enumerator. Arrays have built-in optimized enumerators. If you disregard that performance hit, you're on the right track, though the consumer can simply do
```csharp
var mutableList = GetNames() as IList<string>;
mutableList[0] = "get rekt bozo";
```
so you're only adding one very thin layer of protection (I didn't intend any innuendos).

> Or... you could keep the GetValues() and GetNames() methods as they are and introduce something else like properties "Values" and "Names" as well to return a cached IReadOnlyList instead. I think it's generally frowned upon if properties do heavy work while it's more accepted when methods do.

The idea of providing an alternative API to get a cached version of the workable data is good. It would still be preferable to be offered a concrete type and not a `IReadOnlyList<>` for the aforementioned reason.

**Comment by AnonymousRetard** [comment]
I would like to read about these "built-in optimized enumerators" so please send a link or resource if you know of one.

The other problem of being able to cast the result back to an array or IList or ICollection or whatever that's actually readable again is something I realized right after posting and reading your reply. That would be solved by ImmutableArray and it does implement IReadOnlyList so if you use that internally unless this "built-in optimized enumerators" is a thing then there shouldn't be much difference what you return at that point.

Something else to consider is that you can multi-target nuget packages and have preprocessor defines for what framework you are using like so:
.csproj example:
`<TargetFrameworks>netstandard2.0;net5.0-windows10.0.19041.0</TargetFrameworks>`

.cs example:
```
#if NETSTANDARD2_0
#else
#endif
```

This way you could have a normal array backing the cached items on .NET framework but utilize ImmutableArray as the backing  field on more modern versions that support it. You'd probably want to return the same type on both implementations though and there IReadonlyList would be useful again because both an array, a list and an ImmutableArray implements it.

**Comment by AlFasGD** [comment]
I like this approach a little more, which acts like a local array pool, and will be a much simpler change to apply.

**Comment by snechaev** [comment]
@Elfocrash I'm afraid that the approach with two arrays is not thread-safe. Developer will be very surprised when the array will be changed "magically" (and actually by the other thread) just during enumeration.  This approach may be extended with ThreadStatic, but there will be possible problems with ThreadPool where the async control flow can jump arount different threads. 
So, I beleive that if we want to safe-to-use solution, then we only have two options:
* stay with the array, but return the new array for each caller
* replace array with something immutable (and break the contract).

**Comment by Elfocrash** [comment]
There is no reason for it to be thread safe. What we are trying to solve here is to give an immutable array experience without breaking the contract. No consumer should be mutating this array in the first place.

**Comment by YuriiBabenko** [comment]
yeah, there is a point to make the private array via `Lazy<T[]>`

**Comment by AlFasGD** [comment]
There is no reason to add the extra overhead of adding multiple methods, `??=` does the job quite fine already.

**Comment by Elfocrash** [comment]
@AlFasGD It actually does because when you copy an array to another array with Array.Copy or Buffer.BlockCopy you copy the references so when you change the second array the first one also changes. You can work around that by iterating over the array with a for loop and setting the value one after the other but that is significantly slower.

**Comment by Elfocrash** [comment]
Interesting, I was debugging this earlier and it worked as described in my previous comment but now I'm trying it again and it seems to be working fine even with [the Array.Copy that I was trying earlier](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQ6DCB7ANtsAbQF0ACAMwEswBnYUgXlKgFMB3E0gb1J3zAB0AQQBeEMCwA0vPAQEAZSgHMAFsADiEllGl85AIVwBDAMYBrXbMEB1FZWAtSAXwDcWK5xosT2KABNGZnYZfkIqWmAFbSVgFWI3NCEwMCMATwEcAAdUgApwumkvH39pfMj5aNiASgT0It8/QgQyJj1BUXEWBLgkAE486jom4hr0Hv76/2HRjDQ4AGZSbQgAWxCCdC50Uh3SDolJbd3FVQ0tHSOdw1MLS9JbexZ0JyA=)
No idea what happened there with my debugger but yeah since that seems to be working as expected you don't need the ImmutableArray. I only added it because I was getting this weird behavior with the normal one

**Comment by AlexBagnolini** [comment]
What about adding new methods called `GetValuesCached()` / `GetNamesCached()` that return `ImmutableArray`s?

Guard it with a preprocessor directive to compile it only for Core 1.1+.
Proper documentation on both the non cached and cached versions detailing that one instantiates a new array each time while the other one always returns the same `ImmutableArray` instance.

Intellisense will show the 2 methods side by side and the developer will make his curated choice.

**Comment by andrewlock** [comment]
> There is no reason for it to be thread safe

I disagree I'm afraid, it's very unusual for `static` methods _not_ to be threadsafe.

> I wonder how reflection does it?

[It's complicated](https://github.com/dotnet/runtime/blob/main/src/coreclr/System.Private.CoreLib/src/System/Enum.CoreCLR.cs#L34-L39) 😅 

> What about adding new methods...

I'm not a fan of this, seems overkill to me.

I appreciate all the feedback from everyone, but to be honest, I'm inclined to not do anything more here, and either use the original approach of the PR or no changes. Using an `T[]` has all the benefits [I described here](https://github.com/andrewlock/NetEscapades.EnumGenerators/pull/21#issuecomment-1151163698). 

The question is whether it is better to cache the array internally, or let users decide how to do it. I'm leaning back to my original position of leaving that up to the consumer. After all, that's what users currently do with `Enum.GetValues<T>()` - you would always cache it by default right? This library is meant to be a "drop in" replacement for the BCL methods, so changing the semantic behaviour isn't great either.

**Comment by AlFasGD** [comment]
> After all, that's what users currently do with `Enum.GetValues<T>()` - you would always cache it by default right?

Yeah because reflection is slow af and the runtime doesn't quite love enums as much as other features.

> This library is meant to be a "drop in" replacement for the BCL methods, so changing the semantic behaviour isn't great either. 

We don't quite change the semantic behavior, we still get the data from somewhere. That data is supposed to be safely stored and then copied over to expose to consumers. It's a risk returning the mutable readonly array, but it offers the best speed, which is the greatest purpose of the generator; quick and statically-coded responses for enum info.

**Comment by juniordiscart** [comment]
@AnonymousRetard 
> I would like to read about these "built-in optimized enumerators" so please send a link or resource if you know of one.

I don't have any documentation to link that explains the topic as a whole, but it's something I've been chipping away at in the past few weeks optimizing several caching classes. I defined a lot of interfaces with `IEnumerable` or `IReadOnlyList` etc. but these generate garbage as the CLR generates a generic iterator object on the heap each time the collection is being iterated over.
* The `List<T>` type specifically has a struct implementation of its iterator, so no heap allocations. As you can see [here](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.enumerator?view=net-6.0), it inherits from `ValueType`. When returning your `List<T>` as an `IReadOnlyList<T>`, and requesting an iterator on that, the struct iterator gets boxed, essentially negating its benefits.
* Arrays on the other hand, as I understood, the CLR [replaces foreach loops with actual for loops](https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/april/essential-net-understanding-csharp-foreach-internals-and-custom-iterators-with-yield). The `GetEnumerator()` method of an array returns an `IEnumerator` object though, so likely this will again allocate memory on the heap if you plan on iterating over an array in a custom way that is not `for` or `foreach`.

**Comment by andrewlock** [comment]
I'm strongly inclined to just update the documentation on the property to say you should cache it as we return a new array each time.

**Comment by ercangorgulu** [comment]
> I'm strongly inclined to just update the documentation on the property to say you should cache it as we return a new array each time.

Instead of that, giving an option to developer could be better. I will come up with a proposal when I get free time.

**Comment by andrewlock** [comment]
> > I'm strongly inclined to just update the documentation on the property to say you should cache it as we return a new array each time.
> 
> Instead of that, giving an option to developer could be better. I will come up with a proposal when I get free time.

Thanks, but I don't see that being an option that's worth adding when there's an easy solution (cache it yourself)

**Comment by AnonymousRetard** [comment]
> @AnonymousRetard
> 
> > I would like to read about these "built-in optimized enumerators" so please send a link or resource if you know of one.
> 
> I don't have any documentation to link that explains the topic as a whole, but it's something I've been chipping away at in the past few weeks optimizing several caching classes. I defined a lot of interfaces with `IEnumerable` or `IReadOnlyList` etc. but these generate garbage as the CLR generates a generic iterator object on the heap each time the collection is being iterated over.
> 
> * The `List<T>` type specifically has a struct implementation of its iterator, so no heap allocations. As you can see [here](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.enumerator?view=net-6.0), it inherits from `ValueType`. When returning your `List<T>` as an `IReadOnlyList<T>`, and requesting an iterator on that, the struct iterator gets boxed because the interface contract specifies the need for an `IEnumerator` object, essentially negating its memory allocation benefits.
> * Arrays on the other hand, as I understood, the CLR [replaces foreach loops with actual for loops](https://docs.microsoft.com/en-us/archive/msdn-magazine/2017/april/essential-net-understanding-csharp-foreach-internals-and-custom-iterators-with-yield). The `GetEnumerator()` method of an array returns an `IEnumerator` object though, so likely this will again allocate memory on the heap if you plan on iterating over an array in a custom way that is not `for` or `foreach`.

Interesting! Thanks for this thorough reply. I took a quick look at the generated code at sharplab.io and yes, when I do foreach on a standard T[] array it gets converted to a while loop. A foreach on a IReadOnlyList though calls .GetEnumerator() instead.

A standard for-loop gets converted to a while loop in both cases, no .GetEnumerator() call. So yes, it does seem like a foreach loop will perform worse on IReadOnlyList compared to T[] or List<T> (which also calls .GetEnumerator() but as you said, it returns a struct implementation).

**Comment by goremykin** [comment]
> I'm strongly inclined to just update the documentation on the property to say you should cache it as we return a new array each time.

I don't see any potential damage from caching. The code of people who are not aware of this problem will work better. People who know about this problem will be able to write less code. Even if someone is already caching results, what harm will this change do?

**Comment by andrewlock** [comment]
> I don't see any potential damage from caching. 

This thread describes the potential damage 🙂 

> > I'm strongly inclined to just update the documentation on the property to say you should cache it as we return a new array each time.
> 
> I don't see any potential damage from caching. The code of people who are not aware of this problem will work better. People who know about this problem will be able to write less code. Even if someone is already caching results, what harm will this change do?
> 
> But on the other hand "people who are not aware of this problem" will not install this package ...

This thread describes the potential damage - it's returning a mutable object (an array) which, if mutated by the end user, could cause strange results.

**Comment by goremykin** [comment]
@andrewlock, And we can't use ImmutableArray because it is not supported by .net framework and also we can't use Nick's solution because it is not thread-safe, right?

**Comment by andrewlock** [comment]
> And we can't use ImmutableArray because it is not supported by .net framework

@goremykin Correct and I wanted to keep the API the same as the existing reflection-based versions. We _could_ use `#if` for NETFramework, but that's kinda horrible for consumers that are multi-targeting

> we can't use Nick's solution because it is not thread-safe, right?

Correct

**Comment by goremykin** [comment]
@andrewlock, Sad, but thanks for the explanation!

**Comment by Zettersten** [comment]
` sb.Append(@"

        public static System.Collections.Generic.IEnumerable<").Append(enumToGenerate.FullyQualifiedName).Append(@"> GetValues()
        {");
        foreach (var member in enumToGenerate.Names)
        {
            sb.Append(@"
                yield return ").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(member.Key).Append(';');
        }

        sb.Append(@"
        }");`

^--- threadsafe
^--- no alloc
^--- readonly

but changes interface...

Thoughts?

**Comment by aleGuardiola** [comment]
> ```csharp
> sb.Append(@"
> 
>         public static System.Collections.Generic.IEnumerable<").Append(enumToGenerate.FullyQualifiedName).Append(@"> GetValues()
>         {");
>         foreach (var member in enumToGenerate.Names)
>         {
>             sb.Append(@"
>                 yield return ").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(member.Key).Append(';');
>         }
> 
>         sb.Append(@"
>         }");
> ```
> 
> ^--- threadsafe
> ^--- no alloc
> ^--- readonly
> 
> but changes interface...
> 
> Thoughts?
> 
> ```csharp
> public enum Colors
> {
>     Red,
>     Green,
>     Blue,
>     Yellow,
> }
> 
> public static class ColorsExtensions
> {
>     public static IEnumerable<Colors> GetValuesFast()
>     {
>         yield return Colors.Red;
>         yield return Colors.Green;
>         yield return Colors.Blue;
>         yield return Colors.Yellow;
>     }
> }
> ```

The problem with this solution is that the API is different than the original, should return an array.

**Comment by Zettersten** [comment]
> > ```cs
> > sb.Append(@"
> > 
> >         public static System.Collections.Generic.IEnumerable<").Append(enumToGenerate.FullyQualifiedName).Append(@"> GetValues()
> >         {");
> >         foreach (var member in enumToGenerate.Names)
> >         {
> >             sb.Append(@"
> >                 yield return ").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(member.Key).Append(';');
> >         }
> > 
> >         sb.Append(@"
> >         }");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ^--- threadsafe
> > ^--- no alloc
> > ^--- readonly
> > but changes interface...
> > Thoughts?
> > ```cs
> > public enum Colors
> > {
> >     Red,
> >     Green,
> >     Blue,
> >     Yellow,
> > }
> > 
> > public static class ColorsExtensions
> > {
> >     public static IEnumerable<Colors> GetValuesFast()
> >     {
> >         yield return Colors.Red;
> >         yield return Colors.Green;
> >         yield return Colors.Blue;
> >         yield return Colors.Yellow;
> >     }
> > }
> > ```
> 
> The problem with this solution is that the API is different than the original, should return an array.

Thank the God's we're only in beta right!

**Comment by aleGuardiola** [comment]
> > > ```cs
> > > sb.Append(@"
> > > 
> > >         public static System.Collections.Generic.IEnumerable<").Append(enumToGenerate.FullyQualifiedName).Append(@"> GetValues()
> > >         {");
> > >         foreach (var member in enumToGenerate.Names)
> > >         {
> > >             sb.Append(@"
> > >                 yield return ").Append(enumToGenerate.FullyQualifiedName).Append('.').Append(member.Key).Append(';');
> > >         }
> > > 
> > >         sb.Append(@"
> > >         }");
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ^--- threadsafe
> > > ^--- no alloc
> > > ^--- readonly
> > > but changes interface...
> > > Thoughts?
> > > ```cs
> > > public enum Colors
> > > {
> > >     Red,
> > >     Green,
> > >     Blue,
> > >     Yellow,
> > > }
> > > 
> > > public static class ColorsExtensions
> > > {
> > >     public static IEnumerable<Colors> GetValuesFast()
> > >     {
> > >         yield return Colors.Red;
> > >         yield return Colors.Green;
> > >         yield return Colors.Blue;
> > >         yield return Colors.Yellow;
> > >     }
> > > }
> > > ```
> > 
> > The problem with this solution is that the API is different than the original, should return an array.
> 
> Thank the God's we're only in beta right!

I mean the original API of .Net Wich is not in beta

**Comment by Zettersten** [comment]
> I mean the original API of .Net Wich is not in beta

I see. GetValues (original .net api) returns an array and therefore we're wanting GetValuesFast to do the same. We're on the same page now - thank you!

**Comment by aleGuardiola** [comment]
> > I mean the original API of .Net Wich is not in beta
> 
> I see. GetValues (original .net api) returns an array and therefore we're wanting GetValuesFast to do the same. We're on the same page now - thank you!
> 
> 
> 

Awesome!!

**Comment by andrewlock** [comment]
As discussed, I'm going to close this as "by design" for now - I'd rather keep the equivalent API of using `Array` and let people cache as they see fit in the consuming code. I've added comments to the API to make it clear that this is the beahviour for now

**Pull request closed without merging**
