### PR TITLE
enum length

### PR DESCRIPTION
**Pull request by tothalexlaszlo**
In order to get the length of an enum, source generator can introduce a public constant variable what is faster.

|               Method |       Mean |     Error |    StdDev | Ratio |  Gen 0 | Allocated |
|--------------------- |-----------:|----------:|----------:|------:|-------:|----------:|
|           EnumLength | 41.9690 ns | 0.2502 ns | 0.2218 ns | 1.000 | 0.0076 |      48 B |
| EnumLengthExtensions |  9.0046 ns | 0.0649 ns | 0.0607 ns | 0.214 | 0.0076 |      48 B |
|   EnumLengthProperty |  0.0214 ns | 0.0046 ns | 0.0043 ns | 0.001 |      - |         - |

### CODE REVIEW

**Comment by adamradocz** [comment]
@andrewlock this is very useful, are you considering to merge this?

**Comment by adamradocz** [comment]
Yes, sounds perfect. :)

**Comment by FroggieFrog** [comment]
I thought maybe it is useful to add a documentation comment which clarifies what this property reflects.
Because it is a non distinct count of the names (if I'm correct).
A user could have an enum defined with different names, but same values.

```csharp
using System;
using System.Linq;

public class Program
{
    public enum Foo
    {
        First = 0,
        Second = 1,
        Third = 1,
    }

    public static void Main()
    {
        var nameCount = Enum.GetNames(typeof(Foo)).Length;
        var valueCount = Enum.GetValues(typeof(Foo)).Length;
        var distinctNameCount = Enum.GetNames(typeof(Foo)).Distinct().Count();
        var distinctValueCount = ((Foo[])Enum.GetValues(typeof(Foo))).Distinct().Count();

        Console.WriteLine($"{nameof(nameCount)}: {nameCount}");
        Console.WriteLine($"{nameof(valueCount)}: {valueCount}");
        Console.WriteLine($"{nameof(distinctNameCount)}: {distinctNameCount}");
        Console.WriteLine($"{nameof(distinctValueCount)}: {distinctValueCount}");
    }
}
```

```console
nameCount: 3
valueCount: 3
distinctNameCount: 3
distinctValueCount: 2
```

**Comment by andrewlock** [comment]
That's a good point. I guess one question I have is: when would you use this 🤔 i.e. when would you want to get the number of names/values but _not_ get the actual name/values themselves?

**Comment by adamradocz** [comment]
I usually use the number of names, when I want to create a new `List<T>` with an initial size of the enum.
I can't think of anything right now, when would I use the distinct value count.

**Comment by andrewlock** [comment]
Thanks all, looks good to me (I added the xmldocs for clarity)

**Pull request merged**
