### PR TITLE
Spanify

### PR DESCRIPTION
**Pull request by adamradocz**
Based on #13 

- [x] Create the `ReadOnlySpan<char>` version of `IsDefined` and `TryParse`
- [x] Add Tests
- [x] Add Benchmarks

@andrewlock Should we keep the string version of the `IsDefined` and `TryParse`? The `ReadOnlySpan<char>` can be used with `string` implicitly.

Edit:
Yes, the string versions should be kept, because they are a little bit faster even tho, they allocate memory.

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4470.0), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Framework 4.8 (4.8.4470.0), X64 RyuJIT


```
|                                     Method |        Mean |     Error |    StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|------------------------------------------- |------------:|----------:|----------:|------:|--------:|-------:|----------:|
|                              EnumIsDefined |    54.94 ns |  0.334 ns |  0.279 ns |  1.00 |    0.00 | 0.0063 |      40 B |
| EnumIsDefinedNameDisplayName | 4,004.48 ns | 18.656 ns | 17.451 ns | 72.85 |    0.28 | 0.1678 |   1,132 B |
|                        ExtensionsIsDefined |    23.56 ns |  0.088 ns |  0.082 ns |  0.43 |    0.00 | 0.0063 |      40 B |
|                    ExtensionsIsDefinedSpan |    41.30 ns |  0.849 ns |  0.943 ns |  0.76 |    0.02 |      - |         - |
|         ExtensionsIsDefinedDisplayNameSpan |    31.57 ns |  0.058 ns |  0.055 ns |  0.57 |    0.00 |      - |         - |

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4470.0), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Framework 4.8 (4.8.4470.0), X64 RyuJIT


```
|                                Method |         Mean |      Error |     StdDev |       Median | Ratio | RatioSD |  Gen 0 | Allocated |
|-------------------------------------- |-------------:|-----------:|-----------:|-------------:|------:|--------:|-------:|----------:|
|                          EnumTryParse |    182.91 ns |   0.724 ns |   0.642 ns |    182.89 ns |  1.00 |    0.00 | 0.0265 |     169 B |
|                    ExtensionsTryParse |     81.41 ns |   1.636 ns |   4.164 ns |     82.94 ns |  0.41 |    0.01 | 0.0063 |      40 B |
|                ExtensionsTryParseSpan |    136.64 ns |   2.719 ns |   3.131 ns |    138.01 ns |  0.74 |    0.02 |      - |         - |
| EnumTryParseDisplayName | 14,371.12 ns | 243.316 ns | 227.598 ns | 14,443.28 ns | 78.52 |    1.28 | 0.1526 |   1,132 B |
|         ExtensionsTryParseDisplayName |     78.45 ns |   1.560 ns |   1.459 ns |     78.92 ns |  0.43 |    0.01 | 0.0049 |      32 B |
|     ExtensionsTryParseDisplayNameSpan |    107.67 ns |   2.171 ns |   2.823 ns |    109.05 ns |  0.58 |    0.02 |      - |         - |

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4470.0), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Framework 4.8 (4.8.4470.0), X64 RyuJIT


```
|                           Method |     Mean |    Error |  StdDev |   Median | Ratio |  Gen 0 | Allocated |
|--------------------------------- |---------:|---------:|--------:|---------:|------:|-------:|----------:|
|           EnumTryParseIgnoreCase | 823.3 ns | 10.09 ns | 9.43 ns | 826.9 ns |  1.00 | 0.0257 |     169 B |
|     ExtensionsTryParseIgnoreCase | 127.9 ns |  0.67 ns | 0.63 ns | 128.0 ns |  0.16 | 0.0060 |      40 B |
| ExtensionsTryParseIgnoreCaseSpan | 182.2 ns |  3.64 ns | 5.77 ns | 185.1 ns |  0.22 |      - |         - |

### CODE REVIEW

**Comment by andrewlock** [comment]
> @andrewlock Should we keep the string version of the IsDefined and TryParse? The ReadOnlySpan<char> can be used with string implicitly.

In principle, I'm 100% with adding Span overloads, but we definitely can't remove the string ones. The trouble is that `ReadOnlySpan<char>` can't be used with all target frameworks (e.g. `net461`, `netstandard2.0`) 🙁 So we'll 

1) definitely need to keep the string overloads
2) either have to _conditionally_ render the span overloads if we're in an environment that supports them, or allow disabling/enabling them. Will need some thought!

**Comment by adamradocz** [comment]
I merged the Master into this branch, plus added the `IsDefined` overloads which was missing from the DisplayName branch.

I think this is also ready to merge, if you OK with it.

**Comment by adamradocz** [comment]
@andrewlock What do you need, do we need to modify this PR?

**Comment by andrewlock** [comment]
Hi @adamradocz, sorry for the delay, been a bit busy! 

Thanks for this, but yeah, I don't think we should force the addition of the System.Memory NuGet 🤔  I think it would be better to `#ifdef` the `netstandard2.0` target instead. Do you feel strongly about it?

**Comment by adamradocz** [comment]
The problem with the `#if` is that it doesn't apply to the generated code properly. The code won't be seen on .NET 4.8, but it won't be visible on .NET 6 either.

**Comment by andrewlock** [comment]
> The code won't be seen on .NET 4.8, but it won't be visible on .NET 6 either.

I'm not sure I follow 🤔 

If we emit code like this:

```csharp
#if NETCOREAPP && !NETCOREAPP2_0 && !NETCOREAPP1_1 && !NETCOREAPP1_0

// code using Span<T>

#endif
```

Then it should compile on all .NET Core2.1+ apps (we shouldn't use NETCOREAPP2_1_OR_GREATER as that's only available in later SDKs)? Am I missing something? 🤔

**Comment by adamradocz** [comment]
I thought the same, but just not working. I uploaded the commit, you can check it.

**Comment by kamronbatman** [comment]
I would love to see this get merged. Any updates?

**Comment by adamradocz** [comment]
The [0bf523c](https://github.com/andrewlock/NetEscapades.EnumGenerators/pull/16/commits/0bf523c792cb96e236960de57a9ce8b549a0d9b9) commit is mergeable. Unfortunately I couldn't remove the `System.Memory` NuGet because the following code somehow doesn't work properly for me.

```
#if NETCOREAPP && !NETCOREAPP2_0 && !NETCOREAPP1_1 && !NETCOREAPP1_0

// code using Span<T>

#endif
```

**Comment by andrewlock** [comment]
Thanks for the update, I'll look into it

**Comment by andrewlock** [comment]
We had a missing `using System;` so I added that in and everything seemed to work 🙂 

I had some issues with the display attribute not working without the System.DataAnnotations.ComponentModel reference though, so added that in for the other target frameworks and evverything worked correctly, will merge shortly!

**Comment by adamradocz** [comment]
OMG, how could I miss that? Thank you! :)

**Comment by andrewlock** [comment]
Just needed another pair of eyes 🙂 no worries! I'm away for a couple of
weeks now but I'll put out a new release as soon as I'm back!

**Pull request merged**
