### PR TITLE
fix: Fixed missing xml documentation.

### LINKED ISSUE #29: Missing xml documentation for non-embedded case

### PR DESCRIPTION
**Pull request by HavenDV**
Closes #29

### CODE REVIEW

**Comment by andrewlock** [comment]
This would apply for a _normal_ project, but it doesn't make any sense in a source generator I don't think, as you never reference it directly 🙁

**Comment by HavenDV** [comment]
Yes, that's right, specifying the xml documentation for the generator itself doesn't make sense.
But I want to note that the fix is aimed at dll with attributes. They will be implicitly attached to the assembly and will be searched for xml documentation for this. Therefore, the fix adds it to the final package. This also implies that documentation generation(`<GenerateDocumentationFile>true</GenerateDocumentationFile>`) for the project with attributes is enabled.

I checked the current version of the generator, the attributes for it did not contain built-in documentation.

**Comment by HavenDV** [comment]
Here is a screenshot from [my generator](https://github.com/HavenDV/DependencyPropertyGenerator) where the attributes are delivered in the same way as yours(with .xml files)
image

**Comment by andrewlock** [comment]
Incorporated this somewhere along the line, thanks!

**Pull request closed without merging**
